<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stop.proto

namespace GPBMetadata;

class Stop
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
D

stop.protopb"
StopB"Z github.com/g41797/memphisgrpc;pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

