<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer.proto

namespace g4197\memphisphp\pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.ConsumeResponse</code>
 */
class ConsumeResponse extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \g4197\memphisphp\pb\Msg $msg
     *     @type \g4197\memphisphp\pb\Status $status
     *     @type \g4197\memphisphp\pb\Wakeup $wakeup
     * }
     */
    public function __construct($data = NULL) {
        \g4197\memphisphp\metadata\Consumer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.Msg msg = 1;</code>
     * @return \g4197\memphisphp\pb\Msg|null
     */
    public function getMsg()
    {
        return $this->readOneof(1);
    }

    public function hasMsg()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.pb.Msg msg = 1;</code>
     * @param \g4197\memphisphp\pb\Msg $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\Msg::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Status status = 2;</code>
     * @return \g4197\memphisphp\pb\Status|null
     */
    public function getStatus()
    {
        return $this->readOneof(2);
    }

    public function hasStatus()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.pb.Status status = 2;</code>
     * @param \g4197\memphisphp\pb\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\Status::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Wakeup wakeup = 3;</code>
     * @return \g4197\memphisphp\pb\Wakeup|null
     */
    public function getWakeup()
    {
        return $this->readOneof(3);
    }

    public function hasWakeup()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.pb.Wakeup wakeup = 3;</code>
     * @param \g4197\memphisphp\pb\Wakeup $var
     * @return $this
     */
    public function setWakeup($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\Wakeup::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

