<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace g4197\memphisphp\pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Msg</code>
 */
class Msg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .pb.Headers headers = 1;</code>
     */
    protected $headers = null;
    /**
     * Generated from protobuf field <code>optional bytes body = 2;</code>
     */
    protected $body = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \g4197\memphisphp\pb\Headers $headers
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \g4197\memphisphp\metadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .pb.Headers headers = 1;</code>
     * @return \g4197\memphisphp\pb\Headers|null
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }

    /**
     * Generated from protobuf field <code>optional .pb.Headers headers = 1;</code>
     * @param \g4197\memphisphp\pb\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return isset($this->body) ? $this->body : '';
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>optional bytes body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

