<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

namespace g4197\memphisphp\pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.RetentionOpt</code>
 */
class RetentionOpt extends \Google\Protobuf\Internal\Message
{
    protected $retentions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \g4197\memphisphp\pb\MaxMessageAgeSecondsRet $mmasret
     *     @type \g4197\memphisphp\pb\MessagesRet $msgret
     *     @type \g4197\memphisphp\pb\BytesRet $bret
     *     @type \g4197\memphisphp\pb\AckBasedRet $abret
     * }
     */
    public function __construct($data = NULL) {
        \g4197\memphisphp\metadata\Station::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.MaxMessageAgeSecondsRet mmasret = 1;</code>
     * @return \g4197\memphisphp\pb\MaxMessageAgeSecondsRet|null
     */
    public function getMmasret()
    {
        return $this->readOneof(1);
    }

    public function hasMmasret()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.pb.MaxMessageAgeSecondsRet mmasret = 1;</code>
     * @param \g4197\memphisphp\pb\MaxMessageAgeSecondsRet $var
     * @return $this
     */
    public function setMmasret($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\MaxMessageAgeSecondsRet::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.MessagesRet msgret = 2;</code>
     * @return \g4197\memphisphp\pb\MessagesRet|null
     */
    public function getMsgret()
    {
        return $this->readOneof(2);
    }

    public function hasMsgret()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.pb.MessagesRet msgret = 2;</code>
     * @param \g4197\memphisphp\pb\MessagesRet $var
     * @return $this
     */
    public function setMsgret($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\MessagesRet::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.BytesRet bret = 3;</code>
     * @return \g4197\memphisphp\pb\BytesRet|null
     */
    public function getBret()
    {
        return $this->readOneof(3);
    }

    public function hasBret()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.pb.BytesRet bret = 3;</code>
     * @param \g4197\memphisphp\pb\BytesRet $var
     * @return $this
     */
    public function setBret($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\BytesRet::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.AckBasedRet abret = 4;</code>
     * @return \g4197\memphisphp\pb\AckBasedRet|null
     */
    public function getAbret()
    {
        return $this->readOneof(4);
    }

    public function hasAbret()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.pb.AckBasedRet abret = 4;</code>
     * @param \g4197\memphisphp\pb\AckBasedRet $var
     * @return $this
     */
    public function setAbret($var)
    {
        GPBUtil::checkMessage($var, \g4197\memphisphp\pb\AckBasedRet::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRetentions()
    {
        return $this->whichOneof("retentions");
    }

}

