<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

namespace g4197\memphisphp\pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.StorageOpt</code>
 */
class StorageOpt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.StorageOpt.StorageType storageType = 1;</code>
     */
    protected $storageType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $storageType
     * }
     */
    public function __construct($data = NULL) {
        \g4197\memphisphp\metadata\Station::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.StorageOpt.StorageType storageType = 1;</code>
     * @return int
     */
    public function getStorageType()
    {
        return $this->storageType;
    }

    /**
     * Generated from protobuf field <code>.pb.StorageOpt.StorageType storageType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStorageType($var)
    {
        GPBUtil::checkEnum($var, \g4197\memphisphp\pb\StorageOpt\StorageType::class);
        $this->storageType = $var;

        return $this;
    }

}

