<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.CreateConsumerRequest</code>
 */
class CreateConsumerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.Station station = 1;</code>
     */
    protected $station = null;
    /**
     * Generated from protobuf field <code>.pb.Consumer consumer = 2;</code>
     */
    protected $consumer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\Station $station
     *     @type \Pb\Consumer $consumer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Consumer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.Station station = 1;</code>
     * @return \Pb\Station|null
     */
    public function getStation()
    {
        return $this->station;
    }

    public function hasStation()
    {
        return isset($this->station);
    }

    public function clearStation()
    {
        unset($this->station);
    }

    /**
     * Generated from protobuf field <code>.pb.Station station = 1;</code>
     * @param \Pb\Station $var
     * @return $this
     */
    public function setStation($var)
    {
        GPBUtil::checkMessage($var, \Pb\Station::class);
        $this->station = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Consumer consumer = 2;</code>
     * @return \Pb\Consumer|null
     */
    public function getConsumer()
    {
        return $this->consumer;
    }

    public function hasConsumer()
    {
        return isset($this->consumer);
    }

    public function clearConsumer()
    {
        unset($this->consumer);
    }

    /**
     * Generated from protobuf field <code>.pb.Consumer consumer = 2;</code>
     * @param \Pb\Consumer $var
     * @return $this
     */
    public function setConsumer($var)
    {
        GPBUtil::checkMessage($var, \Pb\Consumer::class);
        $this->consumer = $var;

        return $this;
    }

}

