<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stop.proto

namespace g4197\memphisphp\metadata;

class Stop
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
v

stop.protopb"
StopBTZ github.com/g41797/memphisgrpc;pb g4197\\memphisphp\\pb‚g4197\\memphisphp\\metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

