// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: consumerservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Station  *Station         `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	Consumer *Consumer        `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Options  *ConsumingOpions `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consumerservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consumerservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_consumerservice_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeRequest) GetStation() *Station {
	if x != nil {
		return x.Station
	}
	return nil
}

func (x *ConsumeRequest) GetConsumer() *Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *ConsumeRequest) GetOptions() *ConsumingOpions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConsumeMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ConsumeMessages_Start
	//	*ConsumeMessages_Error
	//	*ConsumeMessages_Stop
	Data isConsumeMessages_Data `protobuf_oneof:"data"`
}

func (x *ConsumeMessages) Reset() {
	*x = ConsumeMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consumerservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMessages) ProtoMessage() {}

func (x *ConsumeMessages) ProtoReflect() protoreflect.Message {
	mi := &file_consumerservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMessages.ProtoReflect.Descriptor instead.
func (*ConsumeMessages) Descriptor() ([]byte, []int) {
	return file_consumerservice_proto_rawDescGZIP(), []int{1}
}

func (m *ConsumeMessages) GetData() isConsumeMessages_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ConsumeMessages) GetStart() *ConsumeRequest {
	if x, ok := x.GetData().(*ConsumeMessages_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ConsumeMessages) GetError() *Status {
	if x, ok := x.GetData().(*ConsumeMessages_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ConsumeMessages) GetStop() *Stop {
	if x, ok := x.GetData().(*ConsumeMessages_Stop); ok {
		return x.Stop
	}
	return nil
}

type isConsumeMessages_Data interface {
	isConsumeMessages_Data()
}

type ConsumeMessages_Start struct {
	Start *ConsumeRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ConsumeMessages_Error struct {
	Error *Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ConsumeMessages_Stop struct {
	Stop *Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

func (*ConsumeMessages_Start) isConsumeMessages_Data() {}

func (*ConsumeMessages_Error) isConsumeMessages_Data() {}

func (*ConsumeMessages_Stop) isConsumeMessages_Data() {}

type ConsumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ConsumeResponse_Msg
	//	*ConsumeResponse_Error
	//	*ConsumeResponse_Stop
	Data isConsumeResponse_Data `protobuf_oneof:"data"`
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consumerservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consumerservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_consumerservice_proto_rawDescGZIP(), []int{2}
}

func (m *ConsumeResponse) GetData() isConsumeResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ConsumeResponse) GetMsg() *Msg {
	if x, ok := x.GetData().(*ConsumeResponse_Msg); ok {
		return x.Msg
	}
	return nil
}

func (x *ConsumeResponse) GetError() *Status {
	if x, ok := x.GetData().(*ConsumeResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ConsumeResponse) GetStop() *Stop {
	if x, ok := x.GetData().(*ConsumeResponse_Stop); ok {
		return x.Stop
	}
	return nil
}

type isConsumeResponse_Data interface {
	isConsumeResponse_Data()
}

type ConsumeResponse_Msg struct {
	Msg *Msg `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type ConsumeResponse_Error struct {
	Error *Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ConsumeResponse_Stop struct {
	Stop *Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

func (*ConsumeResponse_Msg) isConsumeResponse_Data() {}

func (*ConsumeResponse_Error) isConsumeResponse_Data() {}

func (*ConsumeResponse_Stop) isConsumeResponse_Data() {}

var File_consumerservice_proto protoreflect.FileDescriptor

var file_consumerservice_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa1, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x48,
	0x00, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x7a, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x73,
	0x74, 0x6f, 0x70, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x4c, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74,
	0x68, 0x69, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x34, 0x31, 0x37, 0x39, 0x37, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consumerservice_proto_rawDescOnce sync.Once
	file_consumerservice_proto_rawDescData = file_consumerservice_proto_rawDesc
)

func file_consumerservice_proto_rawDescGZIP() []byte {
	file_consumerservice_proto_rawDescOnce.Do(func() {
		file_consumerservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_consumerservice_proto_rawDescData)
	})
	return file_consumerservice_proto_rawDescData
}

var file_consumerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_consumerservice_proto_goTypes = []interface{}{
	(*ConsumeRequest)(nil),  // 0: pb.ConsumeRequest
	(*ConsumeMessages)(nil), // 1: pb.ConsumeMessages
	(*ConsumeResponse)(nil), // 2: pb.ConsumeResponse
	(*Station)(nil),         // 3: pb.Station
	(*Consumer)(nil),        // 4: pb.Consumer
	(*ConsumingOpions)(nil), // 5: pb.ConsumingOpions
	(*Status)(nil),          // 6: pb.Status
	(*Stop)(nil),            // 7: pb.Stop
	(*Msg)(nil),             // 8: pb.Msg
}
var file_consumerservice_proto_depIdxs = []int32{
	3,  // 0: pb.ConsumeRequest.station:type_name -> pb.Station
	4,  // 1: pb.ConsumeRequest.consumer:type_name -> pb.Consumer
	5,  // 2: pb.ConsumeRequest.options:type_name -> pb.ConsumingOpions
	0,  // 3: pb.ConsumeMessages.start:type_name -> pb.ConsumeRequest
	6,  // 4: pb.ConsumeMessages.error:type_name -> pb.Status
	7,  // 5: pb.ConsumeMessages.stop:type_name -> pb.Stop
	8,  // 6: pb.ConsumeResponse.msg:type_name -> pb.Msg
	6,  // 7: pb.ConsumeResponse.error:type_name -> pb.Status
	7,  // 8: pb.ConsumeResponse.stop:type_name -> pb.Stop
	1,  // 9: pb.ConsumerService.Consume:input_type -> pb.ConsumeMessages
	2,  // 10: pb.ConsumerService.Consume:output_type -> pb.ConsumeResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_consumerservice_proto_init() }
func file_consumerservice_proto_init() {
	if File_consumerservice_proto != nil {
		return
	}
	file_status_proto_init()
	file_station_proto_init()
	file_consumer_proto_init()
	file_stop_proto_init()
	file_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_consumerservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consumerservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consumerservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_consumerservice_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_consumerservice_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ConsumeMessages_Start)(nil),
		(*ConsumeMessages_Error)(nil),
		(*ConsumeMessages_Stop)(nil),
	}
	file_consumerservice_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ConsumeResponse_Msg)(nil),
		(*ConsumeResponse_Error)(nil),
		(*ConsumeResponse_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consumerservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consumerservice_proto_goTypes,
		DependencyIndexes: file_consumerservice_proto_depIdxs,
		MessageInfos:      file_consumerservice_proto_msgTypes,
	}.Build()
	File_consumerservice_proto = out.File
	file_consumerservice_proto_rawDesc = nil
	file_consumerservice_proto_goTypes = nil
	file_consumerservice_proto_depIdxs = nil
}
