// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: producerservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Station  *Station  `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	Producer *Producer `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producerservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producerservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_producerservice_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceRequest) GetStation() *Station {
	if x != nil {
		return x.Station
	}
	return nil
}

func (x *ProduceRequest) GetProducer() *Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type ProduceMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ProduceMessages_Start
	//	*ProduceMessages_Msg
	//	*ProduceMessages_Stop
	Data isProduceMessages_Data `protobuf_oneof:"data"`
}

func (x *ProduceMessages) Reset() {
	*x = ProduceMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_producerservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceMessages) ProtoMessage() {}

func (x *ProduceMessages) ProtoReflect() protoreflect.Message {
	mi := &file_producerservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceMessages.ProtoReflect.Descriptor instead.
func (*ProduceMessages) Descriptor() ([]byte, []int) {
	return file_producerservice_proto_rawDescGZIP(), []int{1}
}

func (m *ProduceMessages) GetData() isProduceMessages_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ProduceMessages) GetStart() *ProduceRequest {
	if x, ok := x.GetData().(*ProduceMessages_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ProduceMessages) GetMsg() *Msg {
	if x, ok := x.GetData().(*ProduceMessages_Msg); ok {
		return x.Msg
	}
	return nil
}

func (x *ProduceMessages) GetStop() *Stop {
	if x, ok := x.GetData().(*ProduceMessages_Stop); ok {
		return x.Stop
	}
	return nil
}

type isProduceMessages_Data interface {
	isProduceMessages_Data()
}

type ProduceMessages_Start struct {
	Start *ProduceRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ProduceMessages_Msg struct {
	Msg *Msg `protobuf:"bytes,2,opt,name=msg,proto3,oneof"`
}

type ProduceMessages_Stop struct {
	Stop *Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

func (*ProduceMessages_Start) isProduceMessages_Data() {}

func (*ProduceMessages_Msg) isProduceMessages_Data() {}

func (*ProduceMessages_Stop) isProduceMessages_Data() {}

var File_producerservice_proto protoreflect.FileDescriptor

var file_producerservice_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x61, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x42,
	0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x41, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x28, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x69, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x34, 0x31, 0x37, 0x39, 0x37, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_producerservice_proto_rawDescOnce sync.Once
	file_producerservice_proto_rawDescData = file_producerservice_proto_rawDesc
)

func file_producerservice_proto_rawDescGZIP() []byte {
	file_producerservice_proto_rawDescOnce.Do(func() {
		file_producerservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_producerservice_proto_rawDescData)
	})
	return file_producerservice_proto_rawDescData
}

var file_producerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_producerservice_proto_goTypes = []interface{}{
	(*ProduceRequest)(nil),  // 0: pb.ProduceRequest
	(*ProduceMessages)(nil), // 1: pb.ProduceMessages
	(*Station)(nil),         // 2: pb.Station
	(*Producer)(nil),        // 3: pb.Producer
	(*Msg)(nil),             // 4: pb.Msg
	(*Stop)(nil),            // 5: pb.Stop
	(*Status)(nil),          // 6: pb.Status
}
var file_producerservice_proto_depIdxs = []int32{
	2, // 0: pb.ProduceRequest.station:type_name -> pb.Station
	3, // 1: pb.ProduceRequest.producer:type_name -> pb.Producer
	0, // 2: pb.ProduceMessages.start:type_name -> pb.ProduceRequest
	4, // 3: pb.ProduceMessages.msg:type_name -> pb.Msg
	5, // 4: pb.ProduceMessages.stop:type_name -> pb.Stop
	1, // 5: pb.ProducerService.Produce:input_type -> pb.ProduceMessages
	6, // 6: pb.ProducerService.Produce:output_type -> pb.Status
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_producerservice_proto_init() }
func file_producerservice_proto_init() {
	if File_producerservice_proto != nil {
		return
	}
	file_status_proto_init()
	file_station_proto_init()
	file_producer_proto_init()
	file_stop_proto_init()
	file_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_producerservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_producerservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_producerservice_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ProduceMessages_Start)(nil),
		(*ProduceMessages_Msg)(nil),
		(*ProduceMessages_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_producerservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producerservice_proto_goTypes,
		DependencyIndexes: file_producerservice_proto_depIdxs,
		MessageInfos:      file_producerservice_proto_msgTypes,
	}.Build()
	File_producerservice_proto = out.File
	file_producerservice_proto_rawDesc = nil
	file_producerservice_proto_goTypes = nil
	file_producerservice_proto_depIdxs = nil
}
